# Use the main rust Docker image
FROM rust as build
RUN apt-get update && apt-get -y upgrade
RUN apt-get install libssl-dev
RUN apt-get -y install pkg-config musl musl-dev musl-tools
RUN rustup target add x86_64-unknown-linux-musl

# copy app into Docker image
COPY . /app

# Set the workdirectory
WORKDIR /app

# build the app
RUN cargo build --target x86_64-unknown-linux-musl --release

# use google distroless as runtime image
FROM gcr.io/distroless/cc-debian12

# copy app from builder
COPY --from=build /app/target/x86_64-unknown-linux-musl/release/docker-rust /app/docker-rust
WORKDIR /app

# start the application
CMD ["./docker-rust"]
